/*
* Copyright (C) 2019, Alashov Berkeli
* All rights reserved.
*/

import tm.alashow.buildSrc.App

plugins {
	id("com.android.library")
	id("com.google.devtools.ksp")
	id("kotlin-parcelize")
}

android {
	compileSdkVersion App.compileSdkVersion

	defaultConfig {
		minSdkVersion App.minSdkVersion
	}

	lint {
		disable 'GradleCompatible'
	}
	namespace 'tm.alashow.commonData'
}

dependencies {
	ksp(libs.dagger.compiler)
	ksp(libs.hilt.compiler)

	api(libs.store)

	api(libs.androidx.room.ktx)
	api(libs.androidx.room.paging)
	ksp(libs.androidx.room.compiler)

	api(libs.androidx.datastore.preferences)

	api(project(":modules:base"))
	api(project(":modules:common-domain"))
}
