/*
* Copyright (C) 2021, Alashov Berkeli
* All rights reserved.
*/


import tm.alashow.buildSrc.App
import tm.alashow.buildSrc.Deps

plugins {
	id "com.android.library"
	id "dagger.hilt.android.plugin"
	id "com.google.devtools.ksp"
	id "org.jetbrains.kotlin.plugin.compose"
}

android {
	namespace "tm.alashow.datmusic.ui.downloader"

	compileSdkVersion App.compileSdkVersion

	defaultConfig {
		minSdkVersion App.minSdkVersion
	}

	buildFeatures {
		compose = true
	}
}


dependencies {
	api(project(":modules:common-compose"))
	api(project(":modules:common-ui-theme"))
	api(project(":modules:common-ui-components"))
	api(project(":modules:core-downloader"))
	api(project(":modules:core-ui"))

	implementation(Deps.Dagger.hilt)
	ksp(Deps.Dagger.compiler)
	ksp(Deps.Dagger.hiltCompiler)
}
