/*
* Copyright (C) 2019, Alashov Berkeli
* All rights reserved.
*/

import tm.alashow.buildSrc.App

plugins {
	id("com.android.library")
	id("com.google.devtools.ksp")
}

android {
	compileSdkVersion App.compileSdkVersion

	defaultConfig {
		minSdkVersion App.minSdkVersion
	}

	lint {
		disable 'GradleCompatible'
	}
	namespace 'tm.alashow.commonTesting'
}

dependencies {
	implementation(libs.coil)

	ksp(libs.hilt.compiler)

	api(libs.threetenbp)
	api(libs.androidx.arch.core.testing)
	api(libs.androidx.test.core)
	api(libs.androidx.test.rules)
	api(libs.androidx.test.runner)
	api(libs.androidx.test.junit)
	api(libs.androidx.room.testing)
	api(libs.kotlinx.coroutines.test)
	api(libs.hilt.testing)

	api(libs.junit)
	api(libs.mockito.core)
	api(libs.mockito.kotlin)
	api(libs.mockk)
	api(libs.truth)
	api(libs.turbine)
	api(libs.robolectric)

	api(platform(libs.androidx.compose.bom))
	api(libs.androidx.compose.ui.test.junit)
	debugApi(libs.androidx.compose.ui.test.manifest)
}
