/*
 * Copyright (C) 2021, Alashov Berkeli
 * All rights reserved.
 */
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        google()
        maven { url 'https://maven.fabric.io/public' }
        maven { url 'https://oss.sonatype.org/content/repositories/snapshots' }
        mavenCentral()
    }

    dependencies {
        classpath(libs.gradle.android)
        classpath(libs.kotlin.gradle.plugin)
        classpath(libs.kotlin.compose.compiler.plugin)
        classpath(libs.kotlin.serialization.plugin)
        classpath(libs.kotlin.ksp.plugin)
        classpath(libs.gradle.googleServices)
        classpath(libs.gradle.playPublisher)
        classpath(libs.firebase.crashlytics.gradle)
        classpath(libs.androidx.navigation.safeArgs)
        classpath(libs.hilt.gradle.plugin)
    }
}

plugins {
    alias(libs.plugins.spotless)
    alias(libs.plugins.versions)
    alias(libs.plugins.junit.reporter)
}
allprojects {
    tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).configureEach {
        kotlinOptions {
            jvmTarget = "11"
            freeCompilerArgs += "-Xopt-in=kotlinx.coroutines.ExperimentalCoroutinesApi"
            freeCompilerArgs += "-Xopt-in=kotlinx.coroutines.FlowPreview"
            freeCompilerArgs += "-Xopt-in=kotlin.Experimental"
            freeCompilerArgs += "-Xopt-in=coil.annotation.ExperimentalCoilApi"
            freeCompilerArgs += "-Xopt-in=com.google.accompanist.pager.ExperimentalPagerApi"
        }
    }
    tasks.withType(Test).configureEach {
        failOnNoDiscoveredTests = false
        // TODO: add test logger
    }
}

subprojects {
    configurations.configureEach {
        exclude group: 'org.jetbrains.kotlin', module: 'kotlin-android-extensions-runtime'
        exclude group: 'androidx.appcompat'
        exclude group: 'com.google.android.material', module: 'material'
    }

    apply plugin: 'com.diffplug.spotless'
    spotless {
        kotlin {
            licenseHeaderFile project.rootProject.file('spotless/copyright.kt')
            target "**/*.kt"
            ktlint("0.41.0").userData([
                    'android'        : 'true',
                    'max_line_length': '200',
                    'disabled_rules' : 'no-wildcard-imports'
            ])
        }
        format 'misc', {
            target '**/*.gradle', '**/*.md', '**/.gitignore'
            trimTrailingWhitespace()
            indentWithTabs()
        }
    }

    afterEvaluate { project ->
        if (project.hasProperty("android")) {
            android {
                compileOptions {
                    sourceCompatibility JavaVersion.VERSION_11
                    targetCompatibility JavaVersion.VERSION_11
                }
                defaultConfig {
                    testInstrumentationRunner "tm.alashow.base.testing.AndroidTestRunner"
                }
                testOptions {
                    unitTests {
                        includeAndroidResources = true
                    }
                }
            }
        }
    }
}

Object prop(String propertyName, Object defaultValue) {
    def propertyValue = project.properties[propertyName]
    def envValue = System.getenv(propertyName)
    return propertyValue != null ? propertyValue : (envValue != null ? envValue : defaultValue)
}

def getFile(String... fileNames) {
    for (fileName in fileNames) {
        File file = rootProject.file(fileName)
        if (file.exists()) {
            return file
        }
    }
    return null
}

apply from: file('gradle/projectDependencyGraph.gradle')