/*
* Copyright (C) 2021, Alashov Berkeli
* All rights reserved.
*/

import tm.alashow.buildSrc.App

plugins {
	id("com.android.library")
	id("com.google.devtools.ksp")
	id("org.jetbrains.kotlin.plugin.compose")
}

android {
	compileSdkVersion App.compileSdkVersion

	defaultConfig {
		minSdkVersion App.minSdkVersion
	}

	buildFeatures {
		compose = true
	}

	namespace 'tm.alashow.ui.components'
}

dependencies {
	api(libs.lottie.compose)
	api(project(':modules:common-compose'))
	api(project(":modules:common-ui-theme"))
}
