/*
* Copyright (C) 2021, Alashov Berkeli
* All rights reserved.
*/


import tm.alashow.buildSrc.App
import tm.alashow.buildSrc.Deps

plugins {
	id "com.android.library"
	id "dagger.hilt.android.plugin"
	id "com.google.devtools.ksp"
	id "kotlin-parcelize"
	id "org.jetbrains.kotlin.plugin.compose"
}

android {
	compileSdkVersion App.compileSdkVersion

	defaultConfig {
		minSdkVersion App.minSdkVersion
	}

	buildFeatures {
		compose = true
	}

	namespace 'tm.alashow.datmusic.ui.coreLibrary'
}


dependencies {
	api(project(":modules:core-library"))
	api(project(":modules:common-compose"))
	api(project(":modules:common-ui-theme"))
	api(project(":modules:common-ui-components"))
	api(project(":modules:core-ui-downloader"))
	api(project(":modules:navigation"))

	implementation Deps.Dagger.hilt
	ksp Deps.Dagger.compiler
	ksp Deps.Dagger.hiltCompiler
}
