/*
* Copyright (C) 2021, Alashov Berkeli
* All rights reserved.
*/

import tm.alashow.buildSrc.App

plugins {
	id("com.android.library")
	id("dagger.hilt.android.plugin")
	id("com.google.devtools.ksp")
}

android {
	compileSdkVersion App.compileSdkVersion

	defaultConfig {
		minSdkVersion App.minSdkVersion
	}

	namespace 'tm.alashow.datmusic.downloader'
}

dependencies {
	api(project(":modules:core-media"))

	implementation(libs.hilt.android)
	ksp(libs.dagger.compiler)
	ksp(libs.hilt.compiler)

	testImplementation(project(":modules:common-testing"))
	kspTest(libs.dagger.compiler)
}
