/*
* Copyright (C) 2019, Alashov Berkeli
* All rights reserved.
*/

import tm.alashow.buildSrc.App

plugins {
	id("com.android.library")
	id("com.google.devtools.ksp")
	id("kotlin-parcelize")
	id("org.jetbrains.kotlin.plugin.serialization")
}

android {
	compileSdkVersion App.compileSdkVersion

	defaultConfig {
		minSdkVersion App.minSdkVersion

		vectorDrawables.useSupportLibrary = true
	}

	buildFeatures {
		buildConfig = true
	}

	lint {
		disable 'GradleCompatible'
	}
	namespace 'tm.alashow.baseAndroid'
}

dependencies {
	api(libs.hilt.android)

	// android
	api(libs.androidx.activity.ktx)

	api(libs.androidx.navigation.fragment)
	api(libs.androidx.navigation.ui)

	implementation(libs.androidx.lifecycle.extensions)
	api(libs.androidx.lifecycle.runtime)
	api(libs.androidx.lifecycle.runtime.ktx)
	api(libs.androidx.lifecycle.viewmodel.ktx) {}
	api(libs.androidx.lifecycle.viewmodel.savedstate)

	api(libs.androidx.palette)
	api(libs.androidx.media)
	api(libs.androidx.media3.exoplayer)
	api(libs.androidx.media3.datasource.okhttp)
	api(libs.androidx.media3.session)
	api(libs.media3.ext)

	api(libs.qonversion)

	api(project(":modules:base"))
	api(project(":modules:core-media"))
}
