/*
* Copyright (C) 2019, Alashov Berkeli
* All rights reserved.
*/

import tm.alashow.buildSrc.App

plugins {
	id("com.android.library")
	id("com.google.devtools.ksp")
}

android {
	compileSdkVersion App.compileSdkVersion

	defaultConfig {
		minSdkVersion App.minSdkVersion
	}

	lint {
		disable 'GradleCompatible'
	}
	namespace 'tm.alashow.base'
}

dependencies {
	api(libs.kotlin.stdlib)
	api(libs.kotlinx.serialization.json)
	api(libs.kotlinx.coroutines.core)

	api(libs.coil)
	api(libs.timber)
	api(libs.threetenabp)

	api(libs.dagger)
	ksp(libs.dagger.compiler)
	api(libs.hilt.android)
	ksp(libs.hilt.compiler)

	api(libs.okhttp)
	api(libs.okhttp.loggingInterceptor)
	api(libs.retrofit)
	api(libs.retrofit.adapter.rxjava2)
	api(libs.retroauth)
	api(libs.retrofit.kotlinx.serialization.converter)

	api(libs.androidx.documentfile)
	api(libs.androidx.paging.runtime)
	api(libs.androidx.paging.common)

	api("androidx.annotation:annotation:1.10.0")
	api(platform(libs.firebase.bom))
	api(libs.firebase.messaging)
	api(libs.firebase.config)
	api(libs.firebase.analytics)
	api(libs.firebase.crashlytics)

	api(project(":modules:i18n"))

	testImplementation(project(":modules:common-testing"))
	kspTest(libs.hilt.compiler)
}
