/*
* Copyright (C) 2021, Alashov Berkeli
* All rights reserved.
*/

import tm.alashow.buildSrc.App
import tm.alashow.buildSrc.Deps

plugins {
	id "com.android.library"
	id "com.google.devtools.ksp"
	id "org.jetbrains.kotlin.plugin.compose"
}

android {
	compileSdkVersion App.compileSdkVersion

	defaultConfig {
		minSdkVersion App.minSdkVersion

		vectorDrawables.useSupportLibrary = true
	}

    buildFeatures {
        buildConfig = true
	}

	buildFeatures {
		compose = true
	}

	lint {
		disable 'GradleCompatible'
	}
	namespace 'tm.alashow.common.compose'
}

dependencies {
	api project(":modules:base-android")
	api project(":modules:core-playback")

	// Android
	api platform(Deps.Android.Compose.bom)
	api Deps.Android.navigationCompose
	api Deps.Android.navigationHiltCompose

	api Deps.Android.Compose.ui
	api Deps.Android.Compose.uiUtil
	api Deps.Android.Compose.uiTooling
	api Deps.Android.Compose.foundation
	api Deps.Android.Compose.material
	api Deps.Android.Compose.material3
	api Deps.Android.Compose.materialIcons
	api Deps.Android.Compose.materialIconsExtended
	api Deps.Android.Compose.materialNavigation
	api Deps.Android.Compose.constraintLayout
	api Deps.Android.Compose.activity
	api Deps.Android.Compose.liveData
	api Deps.Android.Compose.paging
	api Deps.Android.Lifecycle.composeViewModels

	// Accompanist
	api Deps.Android.Accompanist.pager
	api Deps.Android.Accompanist.permissions
	api Deps.Android.Accompanist.placeholder
	api Deps.Android.Accompanist.swiperefresh
	api Deps.Android.Accompanist.systemUiController
	api Deps.Android.Accompanist.flowlayout

	// 3rd party
	api Deps.Android.Compose.lottie
	api Deps.Android.Compose.coil
	api Deps.Android.Compose.reorderable
}
