/*
* Copyright (C) 2021, Alashov Berkeli
* All rights reserved.
*/

import tm.alashow.buildSrc.App

plugins {
	id("com.android.library")
	id("com.google.devtools.ksp")
	id("org.jetbrains.kotlin.plugin.compose")
}

android {
	compileSdkVersion App.compileSdkVersion

	defaultConfig {
		minSdkVersion App.minSdkVersion

		vectorDrawables.useSupportLibrary = true
	}

	buildFeatures {
		buildConfig = true
	}

	buildFeatures {
		compose = true
	}

	lint {
		disable 'GradleCompatible'
	}
	namespace 'tm.alashow.common.compose'
}

dependencies {
	api(project(":modules:base-android"))
	api(project(":modules:core-playback"))

	// Android
	api(platform(libs.androidx.compose.bom))
	api(libs.androidx.navigation.compose)
	api(libs.androidx.hilt.navigation.compose)

	api(libs.androidx.compose.ui)
	api(libs.androidx.compose.ui.util)
	api(libs.androidx.compose.ui.tooling)
	api(libs.androidx.compose.foundation)
	api(libs.androidx.compose.material)
	api(libs.androidx.compose.material3)
	api(libs.androidx.compose.material.icons)
	api(libs.androidx.compose.material.iconsExtended)
	api(libs.androidx.compose.material.navigation)
	api(libs.androidx.compose.constraintlayout)
	api(libs.androidx.compose.activity)
	api(libs.androidx.compose.livedata)
	api(libs.androidx.compose.paging)
	api(libs.androidx.lifecycle.viewmodel.compose)

	// Accompanist
	api(libs.accompanist.pager)
	api(libs.accompanist.permissions)
	api(libs.accompanist.placeholder)
	api(libs.accompanist.swiperefresh)
	api(libs.accompanist.systemuicontroller)
	api(libs.accompanist.flowlayout)

	// 3rd party
	api(libs.lottie.compose)
	api(libs.coil.compose)
	api(libs.compose.reorderable)
}