/*
* Copyright (C) 2021, Alashov Berkeli
* All rights reserved.
*/

import tm.alashow.buildSrc.App

plugins {
	id("com.android.library")
	id("dagger.hilt.android.plugin")
	id("com.google.devtools.ksp")
	id("org.jetbrains.kotlin.plugin.compose")
}

android {
	compileSdkVersion App.compileSdkVersion

	defaultConfig {
		minSdkVersion App.minSdkVersion
	}

	buildFeatures {
		compose = true
	}

	namespace 'tm.alashow.navigation'
}

dependencies {
	implementation(libs.turbine)

	implementation(libs.hilt.android)
	ksp(libs.dagger.compiler)
	ksp(libs.hilt.compiler)
	api(project(':modules:common-compose'))
}
