/*
* Copyright (C) 2021, Alashov Berkeli
* All rights reserved.
*/


import tm.alashow.buildSrc.App
import tm.alashow.buildSrc.Deps

plugins {
	id "com.android.library"
	id "dagger.hilt.android.plugin"
	id "com.google.devtools.ksp"
	id "org.jetbrains.kotlin.plugin.compose"
}

android {
	compileSdkVersion App.compileSdkVersion

	defaultConfig {
		minSdkVersion App.minSdkVersion
	}

	buildFeatures {
		compose = true
	}

	namespace 'tm.alashow.navigation'
}


dependencies {
	implementation Deps.Testing.turbine

	implementation Deps.Dagger.hilt
	ksp Deps.Dagger.compiler
	ksp Deps.Dagger.hiltCompiler
	api project(':modules:common-compose')

}
