name: Android CI
on: [push]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      - name: Setup Android SDK
        uses: android-actions/setup-android@v4

      - name: Run Tests
        uses: burrunan/gradle-cache-action@v3.0.2
        with:
          gradle-dependencies-cache-key: |
            gradle/libs.versions.toml
          concurrent: true
          arguments: |
            spotlessCheck
            testDebug

      - name: Copy build reports
        if: always()
        run: |
          mkdir -p build-reports
          find . -name "reports" -exec cp -r {} build-reports/ \;
      - name: Upload build reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-reports
          path: build-reports

      - name: Copy test results
        if: always()
        run: |
          mkdir -p junit
          find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} junit/ \;
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-results
          path: junit